require ('dotenv').config();

const express = require('express');
const userRoutes = require('./routes/userRoutes');
const app = express();
const port = process.env.PORT || 3000;

app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use('/api', userRoutes);

// Definiendo las  Habitaciones
// ---------------------------
const capacity = [];
const Room = require('./models/model');
capacity.push (new Room ("Hotel Miramar Hab 101", 2, 2, "", ""));
capacity.push (new Room ("Hotel Miramar Hab 102", 4, 1, "", ""));
capacity.push (new Room ("Hotel Miramar Hab 103", 6, 2, "", ""));
capacity.push (new Room ("Hotel Miramar Hab 104", 2, 1, "", ""));
capacity.push (new Room ("Hotel Miramar Hab 105", 4, 2, "", ""));
capacity.push (new Room ("Hotel Miramar Hab 106", 6, 1, "", ""));
capacity.push (new Room ("Hotel Miramar Hab 107", 2, 2, "", ""));
capacity.push (new Room ("Hotel Miramar Hab 108", 4, 1, "", ""));
capacity.push (new Room ("Hotel Miramar Hab 109", 6, 2, "", ""));
capacity.push (new Room ("Hotel Miramar Hab 110", 2, 1, "", ""));
capacity.push (new Room ("Hotel Miramar Hab 201", 2, 2, "", ""));
capacity.push (new Room ("Hotel Miramar Hab 202", 4, 1, "", ""));
capacity.push (new Room ("Hotel Miramar Hab 203", 6, 2, "", ""));
capacity.push (new Room ("Hotel Miramar Hab 204", 2, 1, "", ""));
capacity.push (new Room ("Hotel Miramar Hab 205", 4, 2, "", ""));
capacity.push (new Room ("Hotel Miramar Hab 206", 6, 1, "", ""));
capacity.push (new Room ("Hotel Miramar Hab 207", 2, 2, "", ""));
capacity.push (new Room ("Hotel Miramar Hab 208", 4, 1, "", ""));
capacity.push (new Room ("Hotel Miramar Hab 209", 6, 2, "", ""));
capacity.push (new Room ("Hotel Miramar Hab 210", 2, 1, "", ""));
capacity.push (new Room ("Hotel Miramar Hab 301", 2, 2, "", ""));
capacity.push (new Room ("Hotel Miramar Hab 302", 4, 1, "", ""));
capacity.push (new Room ("Hotel Miramar Hab 303", 6, 2, "", ""));
capacity.push (new Room ("Hotel Miramar Hab 304", 2, 1, "", ""));
capacity.push (new Room ("Hotel Miramar Hab 305", 4, 2, "", ""));
capacity.push (new Room ("Hotel Miramar Hab 306", 6, 1, "", ""));
capacity.push (new Room ("Hotel Miramar Hab 307", 2, 2, "", ""));
capacity.push (new Room ("Hotel Miramar Hab 308", 4, 1, "", ""));
capacity.push (new Room ("Hotel Miramar Hab 309", 6, 2, "", ""));
capacity.push (new Room ("Hotel Miramar Hab 310", 2, 1, "", ""));
capacity.push (new Room ("Hotel Miramar Hab 401", 2, 2, "", ""));
capacity.push (new Room ("Hotel Miramar Hab 402", 4, 1, "", ""));
capacity.push (new Room ("Hotel Miramar Hab 403", 6, 2, "", ""));
capacity.push (new Room ("Hotel Miramar Hab 404", 2, 1, "", ""));
capacity.push (new Room ("Hotel Miramar Hab 405", 4, 2, "", ""));
capacity.push (new Room ("Hotel Miramar Hab 406", 6, 1, "", ""));
capacity.push (new Room ("Hotel Miramar Hab 407", 2, 2, "", ""));
capacity.push (new Room ("Hotel Miramar Hab 408", 4, 1, "", ""));
capacity.push (new Room ("Hotel Miramar Hab 409", 6, 2, "", ""));
capacity.push (new Room ("Hotel Miramar Hab 410", 2, 1, "", ""));
capacity.push (new Room ("Hotel Miramar Hab 501", 2, 2, "", ""));
capacity.push (new Room ("Hotel Miramar Hab 502", 4, 1, "", ""));
capacity.push (new Room ("Hotel Miramar Hab 503", 6, 2, "", ""));
capacity.push (new Room ("Hotel Miramar Hab 504", 2, 1, "", ""));
capacity.push (new Room ("Hotel Miramar Hab 505", 4, 2, "", ""));
capacity.push (new Room ("Hotel Miramar Hab 506", 6, 1, "", ""));
capacity.push (new Room ("Hotel Miramar Hab 507", 2, 2, "", ""));
capacity.push (new Room ("Hotel Miramar Hab 508", 4, 1, "", ""));
capacity.push (new Room ("Hotel Miramar Hab 509", 6, 2, "", ""));
capacity.push (new Room ("Hotel Miramar Hab 510", 2, 1, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 101", 2, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 102", 4, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 103", 6, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 104", 2, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 105", 4, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 106", 6, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 107", 2, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 108", 4, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 109", 6, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 110", 2, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 201", 2, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 202", 4, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 203", 6, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 204", 2, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 205", 4, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 206", 6, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 207", 2, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 208", 4, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 209", 6, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 210", 2, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 301", 2, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 302", 4, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 303", 6, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 304", 2, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 305", 4, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 306", 6, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 307", 2, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 308", 4, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 309", 6, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 310", 2, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 401", 2, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 402", 4, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 403", 6, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 404", 2, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 405", 4, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 406", 6, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 407", 2, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 408", 4, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 409", 6, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 410", 2, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 501", 2, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 502", 4, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 503", 6, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 504", 2, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 505", 4, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 506", 6, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 507", 2, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 508", 4, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 509", 6, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 510", 2, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 601", 2, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 602", 4, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 603", 6, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 604", 2, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 605", 4, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 606", 6, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 607", 2, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 608", 4, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 609", 6, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 610", 2, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 701", 2, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 702", 4, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 703", 6, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 704", 2, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 705", 4, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 706", 6, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 707", 2, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 708", 4, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 709", 6, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 710", 2, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 801", 2, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 802", 4, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 803", 6, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 804", 2, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 805", 4, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 806", 6, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 807", 2, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 808", 4, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 809", 6, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 810", 2, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 901", 2, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 902", 4, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 903", 6, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 904", 2, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 905", 4, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 906", 6, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 907", 2, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 908", 4, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 909", 6, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 910", 2, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1001", 2, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1002", 4, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1003", 6, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1004", 2, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1005", 4, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1006", 6, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1007", 2, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1008", 4, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1009", 6, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1010", 2, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1101", 2, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1102", 4, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1103", 6, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1104", 2, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1105", 4, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1106", 6, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1107", 2, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1108", 4, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1109", 6, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1110", 2, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1201", 2, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1202", 4, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1203", 6, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1204", 2, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1205", 4, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1206", 6, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1207", 2, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1208", 4, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1209", 6, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1210", 2, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1301", 2, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1302", 4, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1303", 6, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1304", 2, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1305", 4, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1306", 6, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1307", 2, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1308", 4, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1309", 6, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1310", 2, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1401", 2, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1402", 4, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1403", 6, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1404", 2, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1405", 4, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1406", 6, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1407", 2, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1408", 4, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1409", 6, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1410", 2, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1501", 2, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1502", 4, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1503", 6, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1504", 2, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1505", 4, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1506", 6, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1507", 2, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1508", 4, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1509", 6, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1510", 2, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1601", 2, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1602", 4, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1603", 6, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1604", 2, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1605", 4, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1606", 6, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1607", 2, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1608", 4, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1609", 6, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1610", 2, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1701", 2, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1702", 4, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1703", 6, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1704", 2, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1705", 4, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1706", 6, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1707", 2, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1708", 4, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1709", 6, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1710", 2, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1801", 2, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1802", 4, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1803", 6, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1804", 2, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1805", 4, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1806", 6, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1807", 2, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1808", 4, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1809", 6, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1810", 2, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1901", 2, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1902", 4, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1903", 6, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1904", 2, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1905", 4, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1906", 6, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1907", 2, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1908", 4, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1909", 6, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 1910", 2, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 2001", 2, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 2002", 4, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 2003", 6, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 2004", 2, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 2005", 4, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 2006", 6, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 2007", 2, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 2008", 4, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 2009", 6, 2, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 2010", 2, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 2101", 10, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 2102", 10, 4, "", ""));
capacity.push (new Room ("Hotel Casino Enjoy Hab 2103", 10, 4, "", ""));
//capacity.forEach ((valor) => console.log(valor));
console.log ('Total de  Habitaciones -> ' + capacity.length);
module.exports = capacity
// FIN Definiendo las  Habitaciones
// -------------------------------

app.listen(port, () => console.log('Open port -> ' + port));

// http:localhost:3001/api/usuario