require('dotenv').config();
const port = process.env.PORT || 3000;

const express = require('express');
const userRoutes = require('./routes/userRoutes');
const app = express();

app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use('/api', userRoutes)

// Inventario de habitaciones por Hotel

const arrCapacity = [];
const Capacity = require('./models/modelCapacity');

arrCapacity.push (new Capacity ('Enjoy',   101, 'Standard',  80, 2, 1, 'Available'));
arrCapacity.push (new Capacity ('Enjoy',   102, 'Gold',     140, 4, 2, 'Available'));
arrCapacity.push (new Capacity ('Enjoy',   103, 'Platinum', 200, 6, 3, 'Available'));
arrCapacity.push (new Capacity ('Enjoy',   104, 'Standard',  80, 2, 1, 'Available'));
arrCapacity.push (new Capacity ('Enjoy',   105, 'Gold',     140, 4, 2, 'Available'));
arrCapacity.push (new Capacity ('Enjoy',   106, 'Platinum', 200, 6, 3, 'Available'));
arrCapacity.push (new Capacity ('Enjoy',   107, 'Standard',  80, 2, 1, 'Available'));
arrCapacity.push (new Capacity ('Enjoy',   108, 'Gold',     140, 4, 2, 'Available'));
arrCapacity.push (new Capacity ('Enjoy',   109, 'Platinum', 200, 6, 3, 'Available'));
arrCapacity.push (new Capacity ('Enjoy',   110, 'Standard',  80, 2, 1, 'Available'));
arrCapacity.push (new Capacity ('Enjoy',   201, 'Standard',  80, 2, 1, 'Bloqued'));
arrCapacity.push (new Capacity ('Enjoy',   202, 'Gold',     140, 4, 2, 'Bloqued'));
arrCapacity.push (new Capacity ('Enjoy',   203, 'Platinum', 200, 6, 3, 'Bloqued'));
arrCapacity.push (new Capacity ('Enjoy',   204, 'Standard',  80, 2, 1, 'Bloqued'));
arrCapacity.push (new Capacity ('Enjoy',   205, 'Gold',     140, 4, 2, 'Bloqued'));
arrCapacity.push (new Capacity ('Enjoy',   206, 'Platinum', 200, 6, 3, 'Bloqued'));
arrCapacity.push (new Capacity ('Enjoy',   207, 'Standard',  80, 2, 1, 'Bloqued'));
arrCapacity.push (new Capacity ('Enjoy',   208, 'Gold',     140, 4, 2, 'Bloqued'));
arrCapacity.push (new Capacity ('Enjoy',   209, 'Platinum', 200, 6, 3, 'Bloqued'));
arrCapacity.push (new Capacity ('Enjoy',   210, 'Standard',  80, 2, 1, 'Bloqued'));
arrCapacity.push (new Capacity ('Enjoy',   301, 'Standard',  80, 2, 1, 'Bloqued'));
arrCapacity.push (new Capacity ('Enjoy',   302, 'Gold',     140, 4, 2, 'Bloqued'));
arrCapacity.push (new Capacity ('Enjoy',   303, 'Platinum', 200, 6, 3, 'Bloqued'));
arrCapacity.push (new Capacity ('Enjoy',   304, 'Standard',  80, 2, 1, 'Bloqued'));
arrCapacity.push (new Capacity ('Enjoy',   305, 'Gold',     140, 4, 2, 'Bloqued'));
arrCapacity.push (new Capacity ('Enjoy',   306, 'Platinum', 200, 6, 3, 'Bloqued'));
arrCapacity.push (new Capacity ('Enjoy',   307, 'Standard',  80, 2, 1, 'Bloqued'));
arrCapacity.push (new Capacity ('Enjoy',   308, 'Gold',     140, 4, 2, 'Bloqued'));
arrCapacity.push (new Capacity ('Enjoy',   309, 'Platinum', 200, 6, 3, 'Bloqued'));
arrCapacity.push (new Capacity ('Enjoy',   310, 'Standard',  80, 2, 1, 'Bloqued'));
arrCapacity.push (new Capacity ('Enjoy',   401, 'Standard',  80, 2, 1, 'Available'));
arrCapacity.push (new Capacity ('Enjoy',   402, 'Gold',     140, 4, 2, 'Available'));
arrCapacity.push (new Capacity ('Enjoy',   403, 'Platinum', 200, 6, 3, 'Available'));
arrCapacity.push (new Capacity ('Enjoy',   404, 'Standard',  80, 2, 1, 'Available'));
arrCapacity.push (new Capacity ('Enjoy',   405, 'Gold',     140, 4, 2, 'Available'));
arrCapacity.push (new Capacity ('Enjoy',   406, 'Platinum', 200, 6, 3, 'Available'));
arrCapacity.push (new Capacity ('Enjoy',   407, 'Standard',  80, 2, 1, 'Available'));
arrCapacity.push (new Capacity ('Enjoy',   408, 'Gold',     140, 4, 2, 'Available'));
arrCapacity.push (new Capacity ('Enjoy',   409, 'Platinum', 200, 6, 3, 'Available'));
arrCapacity.push (new Capacity ('Enjoy',   410, 'Standard',  80, 2, 1, 'Available'));
arrCapacity.push (new Capacity ('Enjoy',   501, 'VIP',      400, 8, 3, 'Available'));
arrCapacity.push (new Capacity ('Enjoy',   502, 'VIP',      400, 8, 3, 'Available'));
arrCapacity.push (new Capacity ('Enjoy',   503, 'VIP',      400, 8, 3, 'Available'));
arrCapacity.push (new Capacity ('Enjoy',   504, 'VIP',      400, 8, 3, 'Available'));
arrCapacity.push (new Capacity ('Enjoy',   601, 'VIP',      400, 8, 3, 'Available'));
arrCapacity.push (new Capacity ('Enjoy',   602, 'VIP',      400, 8, 3, 'Available'));
arrCapacity.push (new Capacity ('Enjoy',   603, 'VIP',      400, 8, 3, 'Available'));
arrCapacity.push (new Capacity ('Enjoy',   604, 'VIP',      400, 8, 3, 'Available'));
arrCapacity.push (new Capacity ('Enjoy',   701, 'VIP',      400, 8, 3, 'Available'));
arrCapacity.push (new Capacity ('Enjoy',   702, 'VIP',      400, 8, 3, 'Available'));
arrCapacity.push (new Capacity ('Enjoy',   703, 'VIP',      400, 8, 3, 'Available'));
arrCapacity.push (new Capacity ('Enjoy',   704, 'VIP',      400, 8, 3, 'Available'));
arrCapacity.push (new Capacity ('Enjoy',   801, 'VIP',      400, 8, 3, 'Available'));
arrCapacity.push (new Capacity ('Enjoy',   802, 'VIP',      400, 8, 3, 'Available'));
arrCapacity.push (new Capacity ('Enjoy',   803, 'VIP',      400, 8, 3, 'Available'));
arrCapacity.push (new Capacity ('Enjoy',   804, 'VIP',      400, 8, 3, 'Available'));
arrCapacity.push (new Capacity ('Enjoy',   901, 'VIP',      400, 8, 3, 'Available'));
arrCapacity.push (new Capacity ('Enjoy',   902, 'VIP',      400, 8, 3, 'Available'));
arrCapacity.push (new Capacity ('Enjoy',   903, 'VIP',      400, 8, 3, 'Available'));
arrCapacity.push (new Capacity ('Enjoy',   904, 'VIP',      400, 8, 3, 'Available'));
arrCapacity.push (new Capacity ('Enjoy',  1001, 'VIP',      400, 8, 3, 'Blocked'));
arrCapacity.push (new Capacity ('Enjoy',  1002, 'VIP',      400, 8, 3, 'Blocked'));
arrCapacity.push (new Capacity ('Enjoy',  1003, 'VIP',      400, 8, 3, 'Blocked'));
arrCapacity.push (new Capacity ('Enjoy',  1004, 'VIP',      400, 8, 3, 'Blocked'));

arrCapacity.push (new Capacity ('Dreams',  101, 'Standard',  80, 2, 1, 'Available'));
arrCapacity.push (new Capacity ('Dreams',  102, 'Gold',     140, 4, 2, 'Available'));
arrCapacity.push (new Capacity ('Dreams',  103, 'Platinum', 200, 6, 3, 'Available'));
arrCapacity.push (new Capacity ('Dreams',  104, 'Standard',  80, 2, 1, 'Available'));
arrCapacity.push (new Capacity ('Dreams',  105, 'Gold',     140, 4, 2, 'Available'));
arrCapacity.push (new Capacity ('Dreams',  106, 'Platinum', 200, 6, 3, 'Available'));
arrCapacity.push (new Capacity ('Dreams',  107, 'Standard',  80, 2, 1, 'Available'));
arrCapacity.push (new Capacity ('Dreams',  108, 'Gold',     140, 4, 2, 'Available'));
arrCapacity.push (new Capacity ('Dreams',  109, 'Platinum', 200, 6, 3, 'Available'));
arrCapacity.push (new Capacity ('Dreams',  110, 'Standard',  80, 2, 1, 'Available'));
arrCapacity.push (new Capacity ('Dreams',  201, 'Standard',  80, 2, 1, 'Available'));
arrCapacity.push (new Capacity ('Dreams',  202, 'Gold',     140, 4, 2, 'Available'));
arrCapacity.push (new Capacity ('Dreams',  203, 'Platinum', 200, 6, 3, 'Available'));
arrCapacity.push (new Capacity ('Dreams',  204, 'Standard',  80, 2, 1, 'Available'));
arrCapacity.push (new Capacity ('Dreams',  205, 'Gold',     140, 4, 2, 'Available'));
arrCapacity.push (new Capacity ('Dreams',  206, 'Platinum', 200, 6, 3, 'Available'));
arrCapacity.push (new Capacity ('Dreams',  207, 'Standard',  80, 2, 1, 'Available'));
arrCapacity.push (new Capacity ('Dreams',  208, 'Gold',     140, 4, 2, 'Available'));
arrCapacity.push (new Capacity ('Dreams',  209, 'Platinum', 200, 6, 3, 'Available'));
arrCapacity.push (new Capacity ('Dreams',  210, 'Standard',  80, 2, 1, 'Available'));
arrCapacity.push (new Capacity ('Dreams',  301, 'Standard',  80, 2, 1, 'Available'));
arrCapacity.push (new Capacity ('Dreams',  302, 'Gold',     140, 4, 2, 'Available'));
arrCapacity.push (new Capacity ('Dreams',  303, 'Platinum', 200, 6, 3, 'Available'));
arrCapacity.push (new Capacity ('Dreams',  304, 'Standard',  80, 2, 1, 'Available'));
arrCapacity.push (new Capacity ('Dreams',  305, 'Gold',     140, 4, 2, 'Available'));
arrCapacity.push (new Capacity ('Dreams',  306, 'Platinum', 200, 6, 3, 'Available'));
arrCapacity.push (new Capacity ('Dreams',  307, 'Standard',  80, 2, 1, 'Available'));
arrCapacity.push (new Capacity ('Dreams',  308, 'Gold',     140, 4, 2, 'Available'));
arrCapacity.push (new Capacity ('Dreams',  309, 'Platinum', 200, 6, 3, 'Available'));
arrCapacity.push (new Capacity ('Dreams',  310, 'Standard',  80, 2, 1, 'Available'));
arrCapacity.push (new Capacity ('Dreams',  401, 'Standard',  80, 2, 1, 'Available'));
arrCapacity.push (new Capacity ('Dreams',  402, 'Gold',     140, 4, 2, 'Available'));
arrCapacity.push (new Capacity ('Dreams',  403, 'Platinum', 200, 6, 3, 'Available'));
arrCapacity.push (new Capacity ('Dreams',  404, 'Standard',  80, 2, 1, 'Available'));
arrCapacity.push (new Capacity ('Dreams',  405, 'Gold',     140, 4, 2, 'Available'));
arrCapacity.push (new Capacity ('Dreams',  406, 'Platinum', 200, 6, 3, 'Available'));
arrCapacity.push (new Capacity ('Dreams',  407, 'Standard',  80, 2, 1, 'Available'));
arrCapacity.push (new Capacity ('Dreams',  408, 'Gold',     140, 4, 2, 'Available'));
arrCapacity.push (new Capacity ('Dreams',  409, 'Platinum', 200, 6, 3, 'Available'));
arrCapacity.push (new Capacity ('Dreams',  410, 'Standard',  80, 2, 1, 'Available'));
arrCapacity.push (new Capacity ('Dreams',  501, 'Standard',  80, 2, 1, 'Available'));
arrCapacity.push (new Capacity ('Dreams',  502, 'Gold',     140, 4, 2, 'Available'));
arrCapacity.push (new Capacity ('Dreams',  503, 'Platinum', 200, 6, 3, 'Available'));
arrCapacity.push (new Capacity ('Dreams',  504, 'Standard',  80, 2, 1, 'Available'));
arrCapacity.push (new Capacity ('Dreams',  505, 'Gold',     140, 4, 2, 'Available'));
arrCapacity.push (new Capacity ('Dreams',  506, 'Platinum', 200, 6, 3, 'Available'));
arrCapacity.push (new Capacity ('Dreams',  507, 'Standard',  80, 2, 1, 'Available'));
arrCapacity.push (new Capacity ('Dreams',  508, 'Gold',     140, 4, 2, 'Available'));
arrCapacity.push (new Capacity ('Dreams',  509, 'Platinum', 200, 6, 3, 'Available'));
arrCapacity.push (new Capacity ('Dreams',  510, 'Standard',  80, 2, 1, 'Available'));
arrCapacity.push (new Capacity ('Dreams',  601, 'Standard',  80, 2, 1, 'Available'));
arrCapacity.push (new Capacity ('Dreams',  602, 'Gold',     140, 4, 2, 'Available'));
arrCapacity.push (new Capacity ('Dreams',  603, 'Platinum', 200, 6, 3, 'Available'));
arrCapacity.push (new Capacity ('Dreams',  604, 'Standard',  80, 2, 1, 'Available'));
arrCapacity.push (new Capacity ('Dreams',  605, 'Gold',     140, 4, 2, 'Available'));
arrCapacity.push (new Capacity ('Dreams',  606, 'Platinum', 200, 6, 3, 'Available'));
arrCapacity.push (new Capacity ('Dreams',  607, 'Standard',  80, 2, 1, 'Available'));
arrCapacity.push (new Capacity ('Dreams',  608, 'Gold',     140, 4, 2, 'Available'));
arrCapacity.push (new Capacity ('Dreams',  609, 'Platinum', 200, 6, 3, 'Available'));
arrCapacity.push (new Capacity ('Dreams',  610, 'Standard',  80, 2, 1, 'Available'));
arrCapacity.push (new Capacity ('Dreams',  701, 'VIP',      400, 8, 3, 'Available'));
arrCapacity.push (new Capacity ('Dreams',  702, 'VIP',      400, 8, 3, 'Available'));
arrCapacity.push (new Capacity ('Dreams',  703, 'VIP',      400, 8, 3, 'Available'));
arrCapacity.push (new Capacity ('Dreams',  704, 'VIP',      400, 8, 3, 'Available'));
arrCapacity.push (new Capacity ('Dreams',  801, 'VIP',      400, 8, 3, 'Available'));
arrCapacity.push (new Capacity ('Dreams',  802, 'VIP',      400, 8, 3, 'Available'));
arrCapacity.push (new Capacity ('Dreams',  803, 'VIP',      400, 8, 3, 'Available'));
arrCapacity.push (new Capacity ('Dreams',  804, 'VIP',      400, 8, 3, 'Available'));
arrCapacity.push (new Capacity ('Dreams',  901, 'VIP',      400, 8, 3, 'Available'));
arrCapacity.push (new Capacity ('Dreams',  902, 'VIP',      400, 8, 3, 'Available'));
arrCapacity.push (new Capacity ('Dreams',  903, 'VIP',      400, 8, 3, 'Available'));
arrCapacity.push (new Capacity ('Dreams',  904, 'VIP',      400, 8, 3, 'Available'));
arrCapacity.push (new Capacity ('Dreams', 1001, 'VIP',      400, 8, 3, 'Bloqued'));
arrCapacity.push (new Capacity ('Dreams', 1002, 'VIP',      400, 8, 3, 'Bloqued'));
arrCapacity.push (new Capacity ('Dreams', 1003, 'VIP',      400, 8, 3, 'Bloqued'));
arrCapacity.push (new Capacity ('Dreams', 1004, 'VIP',      400, 8, 3, 'Bloqued'));
arrCapacity.push (new Capacity ('Dreams', 1101, 'VIP',      400, 8, 3, 'Available'));
arrCapacity.push (new Capacity ('Dreams', 1102, 'VIP',      400, 8, 3, 'Available'));
arrCapacity.push (new Capacity ('Dreams', 1103, 'VIP',      400, 8, 3, 'Available'));
arrCapacity.push (new Capacity ('Dreams', 1104, 'VIP',      400, 8, 3, 'Available'));
arrCapacity.push (new Capacity ('Dreams', 1201, 'VIP',      400, 8, 3, 'Available'));
arrCapacity.push (new Capacity ('Dreams', 1202, 'VIP',      400, 8, 3, 'Available'));
arrCapacity.push (new Capacity ('Dreams', 1203, 'VIP',      400, 8, 3, 'Available'));
arrCapacity.push (new Capacity ('Dreams', 1204, 'VIP',      400, 8, 3, 'Available'));

module.exports = arrCapacity;

console.log ('Total habitaciones -> ' + arrCapacity.length);

app.listen(port, () => console.log('Open port -> ' + port));